openapi: 3.0.0
info:
  contact:
    email: 1@makor-capital.com
  description: Project research
  title: Research
  version: 1.0.0
servers:
- description: LOCAL server
  url: http://10.0.0.197:8096
- description: DEV server
  url: http://10.0.0.34:8096
tags:
- name: onboarding
- name: utils
paths:
  /utils/country:
    get:
      description: get countries data
      operationId: get_countries
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/country'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get countries data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/position:
    get:
      description: get positions data
      operationId: get_positions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/position'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get positions data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/state:
    get:
      description: get states data
      operationId: get_states
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/state'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get states data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/regulator:
    get:
      description: get regulators data
      operationId: get_regulators
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/regulator'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get regulators data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/company:
    get:
      description: get companies data
      operationId: get_companies
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/company'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get companies data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/dials:
    get:
      description: get dials data
      operationId: get_dials
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dial'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get dials data
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /utils/assets/{id}:
    get:
      description: get company assets
      operationId: get_assets
      parameters:
      - description: id of the onboarding
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/asset'
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get company assets
      tags:
      - utils
      x-eov-operation-handler: controllers/UtilsController
  /onboarding:
    post:
      operationId: createOnboarding
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/onboarding_create'
        description: body structure
        required: true
      responses:
        "200":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Create contact and onboarding
      tags:
      - onboarding
      x-eov-operation-handler: controllers/OnboardingController
  /onboarding/{id}:
    get:
      description: get onboarding data
      operationId: get_onboarding
      parameters:
      - description: id of the onboarding
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get onboarding data
      tags:
      - onboarding
      x-eov-operation-handler: controllers/OnboardingController
    put:
      description: ' update onboarding by id'
      operationId: updateOnboardingById
      parameters:
      - description: id of the onboarding
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/onboarding_update'
        description: any of the following could be sended.
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: update onboarding by id
      tags:
      - onboarding
      x-eov-operation-handler: controllers/OnboardingController
components:
  schemas:
    onboarding_create:
      properties:
        contact_name:
          example: example
          type: string
        contact_email:
          example:
          - example@gmail.com
          - example2@gmail.com
          items:
            type: string
          type: array
        contact_phone:
          example:
          - dialing_code: "972"
            number: "123456789"
          - dialing_code: "972"
            number: "123456789"
          items:
            $ref: '#/components/schemas/onboarding_create_contact_phone'
          type: array
        company_name:
          example: company
          type: string
      required:
      - company_name
      - email
      - name
      - phone
      type: object
    onboarding_update:
      properties:
        is_agreed:
          type: boolean
        company_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        company_name:
          example: company name
          type: string
        LEI:
          example: xxxx
          type: string
        address:
          $ref: '#/components/schemas/onboarding_update_address'
        country_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        us_state_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        regulator_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        regulation_number:
          example: 123abc
          type: string
        comment:
          example: comment
          type: string
        company_asset:
          $ref: '#/components/schemas/onboarding_update_company_asset'
        contact_position_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        contact_name:
          example: name
          type: string
        contact_email:
          example:
          - example@gmail.com
          - example2@gmail.com
          items:
            type: string
          type: array
        contact_phone:
          example:
          - dialing_code: "972"
            number: "123456789"
          - dialing_code: "972"
            number: "123456789"
          items:
            $ref: '#/components/schemas/onboarding_create_contact_phone'
          type: array
      type: object
    country:
      example:
      - name: Israel
        id: IL
      items:
        properties:
          name:
            type: string
          id:
            type: string
        type: object
      type: array
    position:
      example:
      - name: Trader
        id: 4b3e45da-60a3-11ec-a1a2-d08e7912923c
      items:
        properties:
          name:
            type: string
          id:
            format: uuid
            type: string
        type: object
      type: array
    state:
      example:
      - name: Alabama
        id: AL
      items:
        properties:
          name:
            type: string
          id:
            type: string
        type: object
      type: array
    regulator:
      example:
      - name: FCA
        id: 4b3e45da-60a3-11ec-a1a2-d08e7912923c
      items:
        properties:
          name:
            type: string
          id:
            format: uuid
            type: string
        type: object
      type: array
    company:
      example:
      - name: Enigma
        id: 4b3e45da-60a3-11ec-a1a2-d08e7912923c
      items:
        properties:
          name:
            type: string
          id:
            format: uuid
            type: string
        type: object
      type: array
    dial:
      example:
      - dial_code: "93"
        id: AF
      items:
        properties:
          dial_code:
            type: string
          id:
            type: string
        type: object
      type: array
    asset:
      example:
      - name: Fixed income
        id: 4b3a2d1e-60a3-11ec-a1a2-d08e7912923c
      items:
        properties:
          name:
            type: string
          id:
            format: uuid
            type: string
        type: object
      type: array
    onboarding_create_contact_phone:
      properties:
        dialing_code:
          type: string
        number:
          type: string
      type: object
    onboarding_update_address:
      example:
        lat: 123
        lng: 456
      properties:
        lat:
          type: integer
        lng:
          type: integer
      type: object
    onboarding_update_company_asset:
      example:
        asset_id:
        - 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
        - 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
        is_add: true
      properties:
        asset_ids:
          items:
            format: uuid
            type: string
          type: array
        is_add:
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
    OAuth2:
      flows:
        implicit:
          authorizationUrl: http://localhost:8096
          scopes:
            admin: Grants access to admin operations
            author: Grants access to author operations
            sales: Grants access to sales operations
            compliance: Grants access to compliance operations
            client: Grants access to client operations
            prospect: Grants access to prospect operations
      type: oauth2
