openapi: 3.0.0
info:
  contact:
    email: 1@makor-capital.com
  description: Project research
  title: Research
  version: 1.0.0
servers:
- description: LOCAL server
  url: http://localhost:8096
- description: DEV server
  url: http://10.0.0.34:8096
tags:
- name: onboarding
paths:
  /onboarding:
    post:
      operationId: createOnboarding
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/onboarding_create'
        description: body structure
        required: true
      responses:
        "200":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Create contact and onboarding
      tags:
      - onboarding
      x-eov-operation-handler: controllers/OnboardingController
  /onboarding/{id}:
    put:
      description: ' update onboarding by id'
      operationId: updateOnboardingById
      parameters:
      - description: id of the onboarding
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/onboarding_update'
        description: any of the following could be sended.
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: update onboarding by id
      tags:
      - onboarding
      x-eov-operation-handler: controllers/OnboardingController
components:
  schemas:
    onboarding_create:
      properties:
        contact_name:
          example: example
          type: string
        contact_email:
          example:
          - example@gmail.com
          - example2@gmail.com
          items:
            type: string
          type: array
        contact_phone:
          example:
          - "0500000"
          - "0540000000"
          items:
            type: string
          type: array
        company_name:
          example: company
          type: string
      required:
      - company
      - email
      - name
      - phone
      type: object
    onboarding_update:
      properties:
        is_agreed:
          type: boolean
        company_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        company_name:
          example: company name
          type: string
        LEI:
          example: xxxx
          type: string
        address:
          $ref: '#/components/schemas/onboarding_update_address'
        country_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        us_state_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        regulator_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        regulation_number:
          example: 123abc
          type: string
        comment:
          example: comment
          type: string
        company_asset:
          $ref: '#/components/schemas/onboarding_update_company_asset'
        contact_position_id:
          example: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
          format: uuid
          type: string
        contact_name:
          example: name
          type: string
        contact_email:
          example:
          - example@gmail.com
          - example2@gmail.com
          items:
            type: string
          type: array
        contact_phone:
          example:
          - "0500000000"
          - "0500000001"
          items:
            type: string
          type: array
      type: object
    onboarding_update_address:
      example:
        lat: 123
        lng: 456
      properties:
        lat:
          type: integer
        lng:
          type: integer
      type: object
    onboarding_update_company_asset:
      example:
        asset_id: 4b39a1c4-60a3-11ec-a1a2-d08e7912923c
        is_add: true
      properties:
        asset:
          format: uuid
          type: string
        is_add:
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
    OAuth2:
      flows:
        implicit:
          authorizationUrl: http://localhost:8096
          scopes:
            admin: Grants access to admin operations
            author: Grants access to author operations
            sales: Grants access to sales operations
            compliance: Grants access to compliance operations
            client: Grants access to client operations
            prospect: Grants access to prospect operations
      type: oauth2
